Repository ImLazyC0der/AI-ML_CodeHacks, pull requests merged in 2022-10, with the labels that each got.

#15 FIND-Salgorithm
  AI-ML_Projects/FIND-Salgorithm.py
Labels: hacktoberfest-accepted

#22 K-Nearest Neighbour Algorithm
  K-NearestNeighbourAlgorithm.py
Labels: help wanted, hacktoberfest-accepted

#21 K-Means Algorithm
  AI-ML_Projects/K-Means-Algorithm.py
Labels: hacktoberfest-accepted

#20 Heart Patients Demonstration
  HeartPatientsDemonstration.py
Labels: hacktoberfest-accepted

#19 ACCURACY,PRECISION,AND-RECALL
  ACCURACY,PRECISION,AND-RECALL.py
Labels: hacktoberfest-accepted

#18 Naive Bayesian Classifier-Accuracy
  AI-ML_Projects/Naive-Bayesian-Classifier-Accuracy.py
Labels: hacktoberfest-accepted

#17 BACKPROPAGATION-ALGORITHM
  AI-ML_Projects/BACKPROPAGATION-ALGORITHM.py
Labels: hacktoberfest-accepted

#16 DECISION-TREE
  AI-ML_Projects/DECISION-TREE.py
Labels: hacktoberfest-accepted

#25 Add files via upload
  histogram.py
Labels: question

#27 UsingScikit-LearnPreprocessing.py
  AI-ML_Projects/UsingScikit-LearnPreprocessing.py
Labels: hacktoberfest-accepted
